import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '../components/Navbar'
import { getServerSession } from 'next-auth'
import SessionProvider from '@/utils/SessionProvider'
import NextTopLoader from 'nextjs-toploader'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  const session = await getServerSession()
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <div className='mx-auto gap-2 mb-10'>
            <Navbar />
            <NextTopLoader />
            {children}
          </div>
        </SessionProvider>
      </body>
    </html>
  )
}
